### ISSUE TITLE
Cannot Import BinderKey

### ISSUE THREAD

**Issue by josuebrunel** [josuebrunel/myql-cli#12]
``` shell
Traceback (most recent call last):                                                                                                    
  File "myql-cli.py", line 233, in <module>                                                                                           
    args = vars(parser.parse_args())                                                                                                  
  File "/usr/lib/python2.7/argparse.py", line 1688, in parse_args                                                                     
    args, argv = self.parse_known_args(args, namespace)                                                                               
  File "/usr/lib/python2.7/argparse.py", line 1723, in parse_known_args                                                               
    namespace, args = self._parse_known_args(args, namespace)                                                                         
  File "/usr/lib/python2.7/argparse.py", line 1911, in _parse_known_args                                                              
    positionals_end_index = consume_positionals(start_index)                                                                          
  File "/usr/lib/python2.7/argparse.py", line 1888, in consume_positionals                                                            
    take_action(action, args)                                                                                                         
  File "/usr/lib/python2.7/argparse.py", line 1797, in take_action                                                                    
    action(self, namespace, argument_values, option_string)                                                                           
  File "/usr/lib/python2.7/argparse.py", line 1090, in __call__                                                                       
    namespace, arg_strings = parser.parse_known_args(arg_strings, namespace)                                                          
  File "/usr/lib/python2.7/argparse.py", line 1723, in parse_known_args                                                               
    namespace, args = self._parse_known_args(args, namespace)                                                                         
  File "/usr/lib/python2.7/argparse.py", line 1932, in _parse_known_args                                                              
    stop_index = consume_positionals(start_index)                                                                                     
  File "/usr/lib/python2.7/argparse.py", line 1888, in consume_positionals                                                            
    take_action(action, args)                                                                                                         
  File "/usr/lib/python2.7/argparse.py", line 1797, in take_action                                                                    
    action(self, namespace, argument_values, option_string)                                                                           
  File "myql-cli.py", line 123, in __call__                                                                                           
    module = get_module(module_path)                                                                                                  
  File "/home/yosuke/workspace/myql-cli/utils/utils.py", line 43, in get_module                                                       
    module = imp.load_package('module',path)                                                                                          
  File "/home/yosuke/workspace/myql-cli/congoyql/__init__.py", line 1, in <module>                                                    
    from tables import *                                                                                                              
  File "/home/yosuke/workspace/myql-cli/congoyql/tables.py", line 1, in <module>                                                      
    from myql.contrib.table import TableModel, BinderModel, BinderKey, BinderPage                                                     
ImportError: cannot import name BinderKey                                                       
```

**Comment by josuebrunel** [comment]
**_BinderKey**_ doesn't exist anymore since **mYQL.1.2** though  @josuebrunel :-1:
